---
# tasks file for ansible-onionperf
- name: Install onionperf via pip git
  pip:
    name: "git+{{ onionperf_git_repo }}"
    editable: false
    virtualenv: "{{ onionperf_virtualenv_path }}"
  when: onionperf_virtualenv_path != ""

- name: Clone onionperf
  git:
    repo={{ onionperf_git_repo }}
    dest={{ onionperf_dirpath }}
  when: onionperf_virtualenv_path == ""
