---
# tasks file for ansible-onionperf
- assert:
    that:
      - "virtualenv_path is defined"

- name: Install onionperf via pip git
  pip:
    name: "git+{{ onionperf_git_repo }}"
    editable: false
    virtualenv: "{{ onionperf_virtualenv_path }}"
  when: virtualenv_path is defined
